//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGeneralNotes.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGeneralNotes.Exceptions.MessagesException", typeof(MessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please describe some details about the exercise..
        /// </summary>
        public static string DETAIL_EXERCISE_BLANK {
            get {
                return ResourceManager.GetString("DETAIL_EXERCISE_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This email has already been registered.
        /// </summary>
        public static string EMAIL_ALREADY_REGISTARED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email address provided is not valid..
        /// </summary>
        public static string EMAIL_IS_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid email and/or password..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please inform the equipment that will be used in the exercise..
        /// </summary>
        public static string EQUIPMENT_EXERCISE_BLANK {
            get {
                return ResourceManager.GetString("EQUIPMENT_EXERCISE_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please provide the name of the exercise..
        /// </summary>
        public static string EXERCISE_NAME_BLANK {
            get {
                return ResourceManager.GetString("EXERCISE_NAME_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please enter the number of repetitions of the exercise..
        /// </summary>
        public static string EXERCISE_REPETITIONS_BLANK {
            get {
                return ResourceManager.GetString("EXERCISE_REPETITIONS_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please inform the load to be used in the exercise..
        /// </summary>
        public static string EXERCISE_WEIGHT_IN_WHITE {
            get {
                return ResourceManager.GetString("EXERCISE_WEIGHT_IN_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please incorporate exercise into your routine..
        /// </summary>
        public static string EXERCISES_IN_BLANK {
            get {
                return ResourceManager.GetString("EXERCISES_IN_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a not token?.
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password cannot be empty. Please enter a password..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the name of your exercise routine..
        /// </summary>
        public static string ROUTINE_NAME_IN_BLANK {
            get {
                return ResourceManager.GetString("ROUTINE_NAME_IN_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No routine found..
        /// </summary>
        public static string ROUTINE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROUTINE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user name must be provided..
        /// </summary>
        public static string STUDENT_NAME_IN_WHITE {
            get {
                return ResourceManager.GetString("STUDENT_NAME_IN_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown error.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USER WITHOUT PERMISSION to access the resource.
        /// </summary>
        public static string USER_WITHOUT_PERMISSION {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter your rest time..
        /// </summary>
        public static string WAIT_TIME_IN_BLANK {
            get {
                return ResourceManager.GetString("WAIT_TIME_IN_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The student&apos;s weight must be informed..
        /// </summary>
        public static string WEIGHT_STUDENT_IN_BLANK {
            get {
                return ResourceManager.GetString("WEIGHT_STUDENT_IN_BLANK", resourceCulture);
            }
        }
    }
}
